global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # API Gateway Service
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # CMS Service
  - job_name: 'cms-service'
    static_configs:
      - targets: ['cms-service:4002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Admin Service
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:4003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Application health checks
  - job_name: 'health-checks'
    metrics_path: '/health'
    static_configs:
      - targets: 
        - 'api-gateway:4000'
        - 'auth-service:4001'
        - 'cms-service:4002'
        - 'admin-service:4003'
    scrape_interval: 30s
    scrape_timeout: 10s 